apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: logging-and-metrics
spec:
  http:
    service:
      spec:
        type: ClusterIP
  version: 8.10.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.roles: [ master, data, ingest, transform, remote_cluster_client, ml ]
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  elasticsearch.k8s.elastic.co/cluster-name: logging-and-metrics
              topologyKey: kubernetes.io/hostname
        initContainers:
        # From https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          resources:
            requests:
              memory: 2Gi
              cpu: 1300m
            limits:
              memory: 2Gi
              cpu: 1300m
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: logging-and-metrics
spec:
  elasticsearchRef:
    name: logging-and-metrics
  version: 8.10.2
  count: 1
  http:
    service:
      spec:
        type: LoadBalancer
  podTemplate:
    metadata:
      annotations:
        co.elastic.logs/enabled: "false"
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 2Gi
            cpu: 800m
          limits:
            memory: 4Gi
            cpu: 1500m
