apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops7.fullname" . }}-app
  labels:
    {{- include "devops7.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "devops7.selectorLabels" . | nindent 4 }}
    layer: app
