apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  conf.properties: |
    color=blue
    country=Spain
  conf.json: |
    {"color": "blue", "country": "Spain"}
  otrakey: "value"
  filetext: |
    este es el contenido
    de la clave del configmap
    que representa
    un fichero de texto
