apiVersion: apps/v1 # Version of the API / object specification
kind: Deployment  # Object type: Deployment
metadata: # Metadatos del Deployment
  name: nginx-deployment
  labels: # Deployment labels
    department: support
#  namespace: prueba2
spec: # Deployment SPEC
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # It tells the replication controller to run 
  template:
    metadata: # Metadatos del POD
      labels: # Pod labels
        app: nginx
    spec: # Pod Spec starts here
      tolerations:
        - key: "area"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
      containers: # Containers of the Pod
      - name: nginx
        image: nginx:1.9.1
        ports:
        - containerPort: 80
