{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ include "demo-nginx.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  #- host: nginx.foo.bar.com
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port:
              number: 80
{{- end }}
