apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-nginx.fullname" . }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
{{- include "demo-nginx.selectorLabels" . | nindent 4 }}
    app: nginx        
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
    name: http