apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: default
spec:
  version: 8.10.2
  count: 1
  elasticsearchRef:
    name: logging-and-metrics
  kibanaRef:
    name: logging-and-metrics